### ISSUE TITLE
Invalid value

### ISSUE THREAD

**Issue by khalidid** [SweetOps/terraform-google-storage-bucket#12]
on .terraform/modules/label/main.tf line 81, in locals:
  81:     attributes  = "${lower(join(local.delimiter, local.attributes))}"
    |----------------
    | local.attributes is tuple with 1 element

Invalid value for "lists" parameter: element 0: string required.

**Comment by SweetOps** [comment]
https://github.com/SweetOps/terraform-google-storage-bucket/pull/13

**Comment by SweetOps** [comment]
has been fixed in the new module version https://github.com/SweetOps/terraform-google-storage-bucket/releases/tag/0.3.0
