### ISSUE TITLE
Error: "lifecycle_rule.0.condition.0.is_live": [REMOVED]

### ISSUE THREAD

**Issue by volkmydj** [SweetOps/terraform-google-storage-bucket#17]
Hi!
terraform plan

error
Error: "lifecycle_rule.0.condition.0.is_live": [REMOVED] Please use `with_state` instead

  on .terraform/modules/storage-bucket-prod/SweetOps-terraform-google-storage-bucket-25596b1/main.tf line 13, in resource "google_storage_bucket" "default":
  13: resource "google_storage_bucket" "default" {

my terraform --version 0.12.19
my code:
provider "google" {
  project = var.project
  region  = var.region
}

module "storage-bucket-prod" {
  source        = "SweetOps/storage-bucket/google"
  version       = "0.3.0"
  name          = "storage-bucket-docker-prod"
  location      = "europe-west1"
  force_destroy = true
}

**Comment by alexismosquera** [comment]
Hi there.  Are you planning to fix this issue?

**Comment by SweetOps** [comment]
@alexismosquera , hey :) just came back from vacation, so I'll fix on this week more close to weekends 

@volkmydj , tnx for issue

**Comment by SweetOps** [comment]
https://github.com/SweetOps/terraform-google-storage-bucket/pull/19
